kind: pipeline
type: docker
name: default

steps:
- name: build-frontent-docker
  image: plugins/docker
  settings:
    registry: 
      from_secret: docker-registry
    username: 
      from_secret: docker-username
    password: 
      from_secret: docker-password
    repo: filedrop-fe
    tags: latest
    dry_run: true
    purge: true
    context: ./FileDropFE
    dockerfile: ./FileDropFE/Dockerfile

- name: build-backend-docker
  image: plugins/docker
  settings:
    registry: 
      from_secret: docker-registry
    username: 
      from_secret: docker-username
    password: 
      from_secret: docker-password
    repo: filedrop-be
    tags: latest
    dry_run: true
    purge: true
    context: ./FileDropBE
    dockerfile: ./FileDropBE/Dockerfile

- name: deploy-to-server
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: server-url
    username:
      from_secret: server-username
    port: 
      from_secret: server-port
    key:
      from_secret: server-key 
    command_timeout: 2m
    script:
      - cd /home/docker/FileDrop
      - docker compose pull
      - docker compose down
      - docker compose up -d