kind: pipeline
type: docker
name: frontend

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker-username-public
      password:
        from_secret: docker-password-public
      repo:
        from_secret: docker-repo-fe-public
      tags: latest
      dry_run: false
      purge: true
      context: ./FileDropFE
      dockerfile: ./FileDropFE/Dockerfile

trigger:
  event:
    - custom
    - push
    - pull_request

---
kind: pipeline
type: docker
name: backend

steps:
  - name: pre-build
    image: alpine
    environment:
      APPSETTINGS:
        from_secret: appsettings
    commands:
      - cd ./FileDropBE
      - echo $${APPSETTINGS} > appsettings.json

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker-username-public
      password:
        from_secret: docker-password-public
      repo:
        from_secret: docker-repo-be-public
      tags: latest
      dry_run: false
      purge: true
      context: ./FileDropBE
      dockerfile: ./FileDropBE/Dockerfile

trigger:
  event:
    - custom
    - push
    - pull_request

---
kind: pipeline
type: docker
name: after

steps:
  - name: deploy-to-server
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhook

trigger:
  event:
    - promote
  target:
    - production
