version: "3.3"
services:
  filedrop:
    image: "borelio/filedrop-fe"
    container_name: FileDrop-FE
    networks:
      - filedrop-internal
    depends_on:
      - filedrop-be
    ports:
      - "3091:80"
    restart: unless-stopped
  filedrop-be:
    image: "borelio/filedrop-be"
    container_name: FileDrop-BE
    hostname: FileDrop-BE
    networks:
      - filedrop-internal
    depends_on:
      - filedrop-db
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_ROOT_PASSWORD: "ahlifasdf?234432qr!GUHZG"
    restart: unless-stopped
  filedrop-db:
    image: "mariadb"
    container_name: FileDrop-DB
    hostname: FileDrop-DB
    networks:
      - filedrop-internal
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "ahlifasdf?234432qr!GUHZG"
    restart: unless-stopped

networks:
  filedrop-internal:
